### ISSUE TITLE
"From" pricing not working as expected

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-accommodation-bookings#132] opened 2017-06-23 11:46 UTC
#### Affected ticket(s)
ticket: 590232-zd-woothemes

#### What I expected
When I set a "From" price to be displayed, for that price to be displayed

#### What happened instead
If there is a minimum number of nights of `2` configured, the 'From' price is divided by 2

#### Steps to reproduce the issue
1. An accomodation product exists. It is configured with a display cost of 100
2. That product is configured with a minimum of two nights
3. View the product on the fronted, "From $50.00 per night" is displayed and the expectation is that it would display "From $100.00 per night".

@bor0 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by bor0** [comment] 2017-06-23 12:38
@WillBrubaker can you please re-test this against latest master? I did, and as far as I checked it is not reproducible, but it is reproducible on 1.0.9. I believe #116 (combined with #125) are the reasons for this being fixed.

**Comment by jessepearson** [comment] 2017-06-26 13:49
Closing this, it was fixed in the PRs Boro mentioned.

**Closed by jessepearson** 2017-06-26 13:49 UTC
Labels: [Pri] CRITICAL, [Status] Needs Author Reply, [Type] Bug
