### ISSUE TITLE
Datepicker : unable to pick a check-out date the day after the check-in date if the the check-ouk is marked as unbookable

### ISSUE THREAD

**Issue by ligne13** [woocommerce/woocommerce-accommodation-bookings#191] opened 2018-07-25 09:16 UTC
Example : 
The user wants to book a hotel night from day D to D+1. 
In the back-end the D+1 is marked as unbookable.
![image](https://user-images.githubusercontent.com/81624/43191565-b1883b06-8ffb-11e8-8bd9-5fca167048f0.png)
The user should be able to pick the D+1 as the check-out date. The unbookable range is for the night from D+1 to D+2.
But the datepicker does not allow to pick D+1 as the check-out date.
![image](https://user-images.githubusercontent.com/81624/43191632-d74163e0-8ffb-11e8-91da-2aad79142acb.png)

#### Steps to reproduce the issue

- Create a new Accomodation product (room)
- Add an unbookable range for one specific date (D+1)
- Try to book the room for date D to date D+1
- You cannot pick the D+1 date in the datepicker.

**Comment by jessepearson** [comment] 2018-07-25 12:12
@ligne13 This is not a bug, if a date is marked as unavailable in the settings then it is not able to be used at all. 

I have just added a new idea to the board suggesting what you need. It may take a little bit to show, but here is the link for you to add your vote:
http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/34925098-add-ability-to-block-off-either-check-in-or-out-fo

**Closed by jessepearson** 2018-07-25 12:12 UTC
Labels: [Type] Enhancement, [Type] Help Request

**Comment by ligne13** [comment] 2018-07-25 12:43
Thanks @jessepearson. I've added 3 votes to this feature which is essential to add to the Accommodations plugin. Hoping it will come fast.

**Comment by ligne13** [comment] 2018-12-05 12:48
Hi @jessepearson ,

Any update on this one ?

thanks

**Comment by jessepearson** [comment] 2018-12-06 12:30
@ligne13 I am not a developer, I only support the extensions. The development team takes into account higher voted items when adding new features. Presently this one has only has 7 votes, so it probably has not been added for consideration yet.
