### ISSUE TITLE
Booked accommodation between available check-in and check-out days can be booked more than once

### ISSUE THREAD

**Issue by solstudioim** [woocommerce/woocommerce-accommodation-bookings#285] opened 2022-02-07 11:12 UTC
#### Affected ticket(s)

4751336-zen

#### What I expected

When an accommodation product is configured to have one room for booking, and a resource tied to it with quantity 1, booked accommodation days can't be overridden, or double booking through the previously booked days shouldn't be possible.

#### What happened instead

In this case, the booked accommodation days were 30 June 2022, 2 PM to 3 July 2022, 2 PM. 

We were able to book accommodation from 30 June 2022, 2 PM to 4 July 2022, 2 PM, which is literally double booking the existing accommodation that goes from 30 June 2022, 2 PM through 3 July 2022, 2 PM.

![Screen Capture on 2022-02-07 at 18-06-02](https://user-images.githubusercontent.com/17371139/152776681-298ae89b-0cdb-4d98-9f06-d87e79655a79.gif)

Previously booked accommodation from 30 June 2022, 2 PM to 3 July 2022, 2 PM on the backend calendar:
![Markup 2022-02-07 at 11 29 25](https://user-images.githubusercontent.com/17371139/152776878-2c319e02-7ed0-4f3a-9078-b3e9ca8e056f.png)

Another booking going through the same booked days was possible:
![Markup 2022-02-07 at 11 38 08](https://user-images.githubusercontent.com/17371139/152776993-67f3636b-4b5f-486c-9dc6-8c444ae01722.png)

#### Steps to reproduce the issue

- Create an accommodation product
- Set the room quantity to 1
- Make it virtual, tied to person and resource
- Resource quantity set to 1
- Book 3 days in a room say check-in 30 June 2022, check-out 3 July, pay the booking
- Do another accommodation booking, now select 30 June 2022 as the check-in and 4 July as the check-out time
- Accommodation is possible to be booked twice through the same dates

Setting screenshots:

![Markup on 2022-02-07 at 18:16:16](https://user-images.githubusercontent.com/17371139/152778130-0f9cf29f-828b-4369-897d-2a7787b61bc5.png)

![Markup 2022-02-07 at 18 15 44](https://user-images.githubusercontent.com/17371139/152778020-7e90cd15-7023-45a8-a98e-4bd5689828c4.png)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by nicdwilson** [comment] 2022-02-14 03:22
4772009-zen

**Comment by shaneonabike** [comment] 2022-02-14 14:19
This is also happening to a client I have. There are no resources in our case, but it occurs in the following scenario. Interestingly enough, 

**Previous bookings**
+ 18 July 2022 13:00 - 22 July 2022 10:00
+ 19 July 2022 13:00 - 23 July 2022 10:00

**Product details**
+ Two rooms available, and booking must be at least 2 days

**Test scenario**
+ Attempt to book from 19-21, which is clearly blocked out and I am allowed
+ This happens if the user enters the dates manually or by clicking outside the range (in our case people were entering the dates manually and this was allowing the booking)

**Debugging**
I did a bit of debugging to prove to Woocommerce Support staff that this was actually a bug. Here's what I discovered:

+ Woocommerce Bookings isn't calculating the proper quantities available
+ Line 1552 of  includes/data-objects/class-wc-product-booking.php is misreporting that are 2 spots available and 1 quantity requested
+ **Potential issue** : Your interval calculation in Woocommerce Booking is assuming minutes (same place as code above), and Accommodation passes a value of 1 for the interval. So effectively this is passing, because the first date checked isn't booked + 1 minute is ok. There is some code in there to convert hours to proper minutes, but none for days. My hunch is that this is the core of the issue and it would fail if the interval was correct.

**Comment by shaneonabike** [comment] 2022-02-14 14:26
And here is the settings for one product that is having this issue.

![Selection_001](https://user-images.githubusercontent.com/1126026/153882314-1b867e9c-20bb-4ed3-9c94-d9b0b4a24ceb.png)
![Selection_002](https://user-images.githubusercontent.com/1126026/153882332-d9091472-4faf-4fbd-9b6d-71cb999bf008.png)
![Selection_003](https://user-images.githubusercontent.com/1126026/153882368-8565d123-be5c-4584-b1e3-2ed03eefd4a2.png)

**Comment by shaneonabike** [comment] 2022-02-16 18:14
Hey @jeffpaul 

I realize you set this to status High, but I feel that's kind of urgent to get fixed. It is allowing bookings on a few of my client sites that should be blocked at this point. Then my clients are having to refund the people and tell them that those dates aren't available.

I think I narrowed down the issue, but I really think a developer of this project should just take a quick look. I am sure it's probably like an hour fix.

Thanks so much for your time and consideration.

**Comment by senitak** [comment] 2022-02-16 18:40
Thank you for this. Every day we are down  we are losing bookings!

**Comment by JurisBALANDIS** [comment] 2022-02-18 12:38
Hello, we had the same problems :(

**Our working solution:**
Downgrade WooCommerce Bookings from version 1.15.52 (2022-02-08) to version 1.15.49 (2021-11-30)
with
WooCommerce Accommodation Bookings 1.1.26 (2021-11-30)
All works!

**Comment by shaneonabike** [comment] 2022-02-18 12:41
Wow thanks for the tip @JurisBALANDIS ! Did you simply drop the old one in and remove the new plugin? There weren't any changes to teh db that might have caused problems?

I think I will try this as well. I'm sure that this problem lies more in Woocommerce Bookings from my troubleshooting

**Comment by JurisBALANDIS** [comment] 2022-02-18 12:55
Yes  @shaneonabike, just upload/downgrade WooCommerce Bookings plugin to 1.15.49.
We already noticed the first strangeness in version 1.15.50.

Let's hope to fix the bug in one of the next versions of WCB :P

**Comment by shaneonabike** [comment] 2022-02-18 14:01
Hi there,

I just wrote Woocommerce support to request the previous version of Woocommerce Bookings. They ended up providing me the previous version, and a new beta (no clue why they didn't contact us when we originally reported the issue to test it). It's actually working with the new beta!

I wrote them to see if this is good enough for prime time.

**Comment by faisal-alvi** [comment] 2022-02-24 09:25
Hi everyone, I have investigated and confirmed that all issues mentioned in this ticket are fixed by Booking PR [#3266](https://github.com/woocommerce/woocommerce-bookings/pull/3266). It is ready for a UAT session and soon will be merged and released! 🎊

**Comment by ankitguptaindia** [comment] 2022-03-01 17:00
**QA Update -** 


Cross tested above reported issues with WooCommerce Booking's  'smoke-testing' branch which has fix related to https://github.com/woocommerce/woocommerce-bookings/pull/3266 Above scenarios are working expected. 

**Summary-** Above scenarios will work fine after the next release of Booking extension. 

Can test above scenario with this **Development Version** of Booking extension - [woocommerce-bookings.zip](https://github.com/woocommerce/woocommerce-accommodation-bookings/files/8163383/woocommerce-bookings.zip)

**Comment by IliaDi** [comment] 2022-03-02 09:33
34452986-hc

**Comment by jetoeleid** [comment] 2022-03-15 16:54
Hi everyone!

I would like to report a similar issue on a current site I'm building. It has to do with conference room rentals. Rooms can be rented for up to 12 hours on a single day, from 8 am to 8 pm.

When using the "customer defined blocks" feature, set to 1hr intervals, clients can make overlapping bookings for the rooms.

**Example case:**

1. I book a room for 16th of March for 10 hours, 10am to 8pm.
2. I go to select a different time for the same room on March 16.
3. In the "Start Time" time selection box, the booked times are not available to select, but I can select a starting time for 9 am.
4. In the "End Time" time selection box, all 12 slots are still available, I can select a duration of 5 hrs until 2pm. Which is well inside the previous booking.

**Expected behaviour:**

1. It would seem intuitive that in the "End Time" dropdown the blocks which are already booked should be hidden.
2. If the blocks can't be hidden, then an error message should come up to say that those times are not available for booking.

This occurs whether or not I create a separate resource for each room in addition to the WC product and regardless of the settings used.

As I did not see an exact description fitting my use case above, then I would like to ask whether this fits under the issues that will be resolved in the coming update. Specifically overlapping bookings when using "customer defined blocks" and hours as the time increment.

Furthermore I would like to know when the update is coming - if the issue is not resolved then I cannot use this plugin for the page and the grace period for testing and developing when I can as for a refund is growing smaller by the day.

**Comment by jeffpaul** [comment] 2022-03-15 20:30
@jetoeleid the fix for this is coming in the next Bookings release which should happen soon (and certainly before the end of the month)

**Comment by vikrampm1** [comment] 2022-03-16 14:37
This will be resolved in Bookings 1.15.53

**Closed as completed by vikrampm1** 2022-03-16 14:37 UTC
Labels: priority: high, type: bug

**Comment by csmcneill** [comment] 2022-03-16 17:00
4831440-zen

**Comment by senitak** [comment] 2022-10-11 09:11
Hello,
When?

**Comment by jeffpaul** [comment] 2022-10-11 13:56
@senitak WooCommerce Bookings 1.15.53 was released on March 17, 2022.
