### ISSUE TITLE
The starting day (check-in day) of a partial booked day range is not selectable

### ISSUE THREAD

**Issue by anant1811** [woocommerce/woocommerce-accommodation-bookings#243] opened 2020-02-28 13:15 UTC
Affected ticket: 

2750804-zen

**Describe the bug**

This was checked on a product with WooCommerce Bookings and WooCommerce Bookings Accommodation. 

With check-in and check-out times set as 12 PM and 2 PM respectively, when a booking is made for a date range (Say April 15- April 22), April 15 shows as fully booked (incorrect), while April 22 is partially booked (correct).
![https://d.pr/i/M0CI1Q](https://d.pr/i/M0CI1Q+) 
Full Size: https://d.pr/i/M0CI1Q

HOWEVER, this works fine when using WooCommerce Accommodation Bookings version 1.1.12.

I installed version 1.1.12, and here's a screenshot of the same order:
![https://d.pr/i/9PL1JH](https://d.pr/i/9PL1JH+) 
Full Size: https://d.pr/i/9PL1JH

**To Reproduce**
1. Create an accommodation product (make sure WooCommerce, Bookings and Bookings Accommodation are latest versions)
2. Set Check-in and check-out times
3. Make a booking and then check the calendar, the check-in date will show fully booked instead of partially booked. 
4. Install WooCommerce Accommodation Bookings version 1.1.12 and then check the calendar. 

**Expected behavior**
The starting date should be partially booked.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the extension is active.
- [x] I can reproduce this bug consistently using the steps above.

Setting this to High priority as this would affect many sites using accommodation products.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://woo.local
Site address (URL): http://woo.local
WC Version: 3.9.2
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.2.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.2
WC Database Prefix: wp_
Total Database Size: 36.53MB
Database Data Size: 26.57MB
Database Index Size: 9.96MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.19MB + Index: 0.22MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.02MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 6.44MB + Index: 4.98MB + Engine InnoDB
wp_posts: Data: 2.36MB + Index: 0.38MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_view: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_term_relationships: Data: 0.44MB + Index: 0.31MB + Engine InnoDB
wp_term_taxonomy: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.44MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 3.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 873
aw_workflow: 6
bookable_person: 2
bookable_resource: 7
course: 1
customize_changeset: 2
follow_up_email: 3
global_product_addon: 1
nav_menu_item: 1
page: 19
post: 2
product: 746
product_variation: 63
revision: 18
shop_coupon: 14
shop_order: 98
shop_order_refund: 1
shop_subscription: 17
wc_booking: 23
wc_membership_plan: 1
wc_pickup_location: 1
wcpf_item: 4
wcpf_project: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (5) ###

WooCommerce Accommodation Bookings: by WooCommerce – 1.1.14
WooCommerce Bookings: by WooCommerce – 1.15.12
WooCommerce Subscriptions: by WooCommerce – 3.0.1
WooCommerce: by Automattic – 3.9.2
WordPress Importer: by wordpressdotorg – 0.6.4

### Inactive Plugins (85) ###

AutomateWoo: by WooCommerce – 4.7.4 – Not tested with the active version of WooCommerce
AutomateWoo: by WooCommerce – 4.7.2 – Not tested with the active version of WooCommerce
AutomateWoo - Subscriptions Add-on: by Prospress Inc. – 1.0.1 – Not tested with the active version of WooCommerce
Code Snippets: by Code Snippets Pro – 2.14.0
Customizer Reset: by WPZOOM – 1.0.1
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.1
Follow-Up Emails: by WooCommerce – 4.8.20 – Not tested with the active version of WooCommerce
Gravity Forms: by rocketgenius – 2.4.5.2
Product Filters for WooCommerce: by Nexter – 1.1.16 – Not tested with the active version of WooCommerce
Sensei LMS: by Automattic – 2.2.1 – 2.4.0 is available
Storefront Mega Menus: by WooCommerce – 1.6.2 – Not tested with the active version of WooCommerce
Storefront Parallax Hero: by WooCommerce – 1.5.7
User Switching: by John Blackbourn & contributors – 1.5.3
WooCommerce: by Automattic – 4.0.0-beta.1
WooCommerce Additional Variation Images: by WooCommerce – 1.7.17 – Not tested with the active version of WooCommerce
WooCommerce Additional Variation Images: by WooCommerce – 1.7.17 – Not tested with the active version of WooCommerce
WooCommerce Admin: by WooCommerce – 0.21.0 – Not tested with the active version of WooCommerce
WooCommerce Advanced Ajax Layered Navigation: by WooCommerce – 1.4.18 – Not tested with the active version of WooCommerce
WooCommerce All Products For Subscriptions: by SomewhereWarm – 2.4.4 – Not tested with the active version of WooCommerce
WooCommerce Amazon Fulfillment: by Never Settle – 3.2.9 – Not tested with the active version of WooCommerce
WooCommerce Australia Post Shipping: by WooCommerce – 2.4.16 – Not tested with the active version of WooCommerce
WooCommerce Beta Tester: by WooCommerce – 2.0.1 – Not tested with the active version of WooCommerce
WooCommerce Bookings Availability: by WooCommerce – 1.1.6
WooCommerce Box Office: by WooCommerce – 1.1.16
WooCommerce Box Office: by WooCommerce – 1.1.15 – Not tested with the active version of WooCommerce
WooCommerce Box Office: by WooCommerce – 1.1.15 – Not tested with the active version of WooCommerce
WooCommerce Brands: by WooCommerce – 1.6.12
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.26 – Not tested with the active version of WooCommerce
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.26 – Not tested with the active version of WooCommerce
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.5.7 – Not tested with the active version of WooCommerce
WooCommerce Currency Converter: by WooCommerce – 1.6.16 – Not tested with the active version of WooCommerce
WooCommerce Deposits: by WooCommerce – 1.4.15 – Not tested with the active version of WooCommerce
WooCommerce Dropshipping: by WooCommerce – 1.2.21 – Not tested with the active version of WooCommerce
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.15 – Not tested with the active version of WooCommerce
WooCommerce Email Customizer: by WooCommerce – 1.1.12 – Not tested with the active version of WooCommerce
WooCommerce FedEx Shipping: by WooCommerce – 3.4.24 – Not tested with the active version of WooCommerce
WooCommerce Gravity Forms Product Add-Ons: by Lucas Stark – 3.3.9 – Not tested with the active version of WooCommerce
WooCommerce Measurement Price Calculator: by SkyVerge – 3.16.2 – Not tested with the active version of WooCommerce
WooCommerce Measurement Price Calculator: by SkyVerge – 3.17.0 – Not tested with the active version of WooCommerce
WooCommerce Memberships: by SkyVerge – 1.16.2 – Not tested with the active version of WooCommerce
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.12 – Not tested with the active version of WooCommerce
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.13
WooCommerce MyGate Gateway: by WooCommerce – 1.2.15 – Not tested with the active version of WooCommerce
WooCommerce New Zealand Post: by WooCommerce – 1.3.6 – Not tested with the active version of WooCommerce
WooCommerce One Page Checkout: by Automattic – 1.7.1 – Not tested with the active version of WooCommerce
WooCommerce Order Barcodes: by Automattic – 1.3.13 – Not tested with the active version of WooCommerce
WooCommerce Order Status Control: by SkyVerge – 1.12.0 – Not tested with the active version of WooCommerce
WooCommerce PayFast Gateway: by WooCommerce – 1.4.14 – Not tested with the active version of WooCommerce
WooCommerce Payment Gateway Based Fees: by InoPlugs – 3.1.10 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.11 – 1.6.20 is available – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.18 – 1.6.20 is available – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.17 – 1.6.20 is available – Not tested with the active version of WooCommerce
WooCommerce PDF Invoices: by Andrew Benbow – 4.1.10 – Not tested with the active version of WooCommerce
WooCommerce Points and Rewards: by WooCommerce – 1.6.25 – Not tested with the active version of WooCommerce
WooCommerce Pre-Orders: by WooCommerce – 1.5.20 – Not tested with the active version of WooCommerce
WooCommerce Pre-Orders: by WooCommerce – 1.5.20 – Not tested with the active version of WooCommerce
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.8.1
WooCommerce Product Add-ons: by WooCommerce – 3.0.19 – Not tested with the active version of WooCommerce
WooCommerce Product Bundles: by SomewhereWarm – 5.13.1 – Not tested with the active version of WooCommerce
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.30 – Not tested with the active version of WooCommerce
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.31
WooCommerce Product Reviews Pro: by SkyVerge – 1.15.0 – Not tested with the active version of WooCommerce
WooCommerce Product Vendors: by WooCommerce – 2.1.22 – Not tested with the active version of WooCommerce
WooCommerce Quick View: by WooCommerce – 1.2.6
WooCommerce Sales Report Email: by WooCommerce – 1.1.10 – Not tested with the active version of WooCommerce
WooCommerce Sales Report Email: by WooCommerce – 1.1.10 – Not tested with the active version of WooCommerce
WooCommerce Shipment Tracking: by WooCommerce – 1.6.17 – Not tested with the active version of WooCommerce
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.4 – Not tested with the active version of WooCommerce
WooCommerce Slack: by WooCommerce – 1.1.16
WooCommerce Smart Refunder: by WooCommerce – 1.4.1 – Not tested with the active version of WooCommerce
WooCommerce Square: by WooCommerce – 2.0.8 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.3.0 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Automattic – 2.6.5 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Automattic – 2.6.3 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions Gifting: by WooCommerce – 2.1.0 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions Gifting: by WooCommerce – 2.1.0 – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.18 – Not tested with the active version of WooCommerce
WooCommerce URL Coupons: by SkyVerge – 2.9.1
WooCommerce USPS Shipping: by WooCommerce – 4.4.35 – Not tested with the active version of WooCommerce
WooCommerce USPS Shipping: by WooCommerce – 4.4.36
WooCommerce Xero Integration: by WooCommerce – 1.7.23 – Not tested with the active version of WooCommerce
Wordfence Security: by Wordfence – 7.4.1
WP Crontrol: by John Blackbourn & crontributors – 1.7.1
WP Mail Logging: by Christian Zöller – 1.9.1
WP Mail Logging: by MailPoet – 1.9.5

### Must Use Plugins (1) ###

Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 4
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page visibility should be public

### Theme ###

Name: Storefront
Version: 2.5.3 – 2.5.5 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: http://woo.local
Subscription Statuses: wc-active: 1
wc-on-hold: 13
wc-cancelled: 3

WooCommerce Account Connected: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — New York

### Subscriptions by Payment Gateway ###

Direct bank transfer: wc-active: 1
wc-on-hold: 1

Check payments: wc-cancelled: 3
wc-on-hold: 9

other: wc-on-hold: 1

### Payment Gateway Support ###

Direct bank transfer: products
Check payments: products
PayPal: subscriptions
gateway_scheduled_payments
subscription_payment_method_change_customer
subscription_cancellation
subscription_suspension
subscription_reactivation
products
refunds

PayPal Reference Transactions Enabled: ❌ No

### Action Scheduler ###

Canceled: 21
Oldest: 2020-02-11 05:54:10 +0000
Newest: 2020-02-27 05:43:03 +0000

Complete: 68
Oldest: 2020-01-29 07:54:55 +0000
Newest: 2020-02-28 12:44:43 +0000

Pending: 2
Oldest: 2020-02-29 07:42:12 +0000
Newest: 2020-03-27 05:23:03 +0000

`
```
</details>

-------------------

- [x] Issue assigned to next milestone.
- [x] Issue assigned a priority (will be assessed by maintainers).

**Comment by jessLundie** [comment] 2020-03-04 00:23
Also seen in 19139697-hc.

**Comment by NickKellett** [comment] 2020-03-04 16:44
The effect of this bug (which I have just observed as well) is that by making the first day of a stay fully booked, another user cannot subsequently select that as their checkout date (even though they are checking out before the first person checks in). Therefore, there will have to be a 1-day gap between every reservation.

**Comment by kg69design** [comment] 2020-03-12 04:18
I confirm the presence of a first-day bug.
--- WooCommerce Accommodation Bookings version 1.1.15
--- WooCommerce Bookings 1.15.11
--- WooCommerce 4.0.0

**Comment by dougaitken** [comment] 2020-03-26 13:16
This was brought up in 2811265-zen and I have tested and replicated. The end date is not booked but the start date shows as booked so another booking cannot end on the start date. 

My check-in time is 1400 and my check-out is 1200 so there is no overlap.

**Comment by pxwm** [comment] 2020-03-26 13:46
Hi,

To confirm I can replicate the problem as per above posts.
I just wanted to check if this is being worked on and if there is an estimated resolution date?

I ask because if I have read correctly no one has been assigned to investigate the issue

Regards
SteveB

**Comment by pxwm** [comment] 2020-03-26 14:03
Hi,

If it helps locate the problem I carried out some testing.

If you configure so the calendar shows on clicking the check-in field.

Then:-

1. Using the example provided by anant1811 who flagged the problem.
2. Then click the check-in field and select the available date, 14th April 2020
3. Then click the check-out date and manually enter the date, 15th Apr 2020 that shows as fully booked but should be showing as 'partially booked' and it allows the booking.

Based on this it may be that it is just the calendar that is displaying incorrectly and not the actual bookings in the database.

If okay I'll check the code to see if I can locate the problem

Regards
SteveB

**Comment by pxwm** [comment] 2020-03-26 18:32
Hi,

We have carried out some further research in to the date picker in previous versions and think we have identified the root cause 

includes/class-wc-accommodation-booking-date-picker.php:100

v1.14 changed line 100 from:-
foreach ( array( 'in', 'out' ) as $which ) {

To:
foreach ( array( 'out' ) as $which ) {


reverted this change and now the check-in date shows correctly as 'partially booked' and allows someone to use this date as a check-out

However unsure why this was changed so it may be breaking something else but hopefully this observation helps.

Regards
SteveB

**Comment by rossviviano** [comment] 2020-03-30 18:00
Another report in 2831378-zd

**Comment by aheckler** [comment] 2020-07-16 15:41
22668353-hc

**Comment by drwpcom** [comment] 2021-03-30 07:35
Another example of this in 26766111-hc to notify when bug fixed.

**Closed** 2023-05-12 12:28 UTC
Labels: priority: high, type: bug
