### ISSUE TITLE
Fully booked days show as partially booked - Day after booking shows partially booked.

### ISSUE THREAD

**Issue by tommyshellberg** [woocommerce/woocommerce-accommodation-bookings#201] opened 2018-10-25 11:18 UTC
#### Affected ticket(s)

1502723-zen
8433091-hc
2108399-zen

#### What I expected

Let's say I have a Yurt that I rent out using Accommodation Bookings - there is only 1 yurt so only one available room.

If I book a date, say just 1 night, then, come back to the Calendar, the check-in date shows "partially booked" - but it's fully booked:

![http://cld.wthms.co/wR5sre](http://cld.wthms.co/wR5sre+)
Image link: http://cld.wthms.co/wR5sre

Additionally, the day *after* shows partially booked(same screenshot above). 

I personally think that it doesn't make sense for Accommodation Bookings to consider something 'partially booked' at all. When you're selecting a room you only care about that room being available from check-in time to check-out time. It doesn't matter if someone had the room before you or after you.

It seems like Accommodation Bookings needs to have some extra logic for these scenarios as it appears to just be using Bookings logic which adds the `partial_booked` class to days which are booked and the day after(because technically the booking bleeds into the next day).

#### Steps to reproduce the issue

* Create a new Accommodation Booking product
* Set its "number of rooms available" to 1
* Set a price
* Book a date, say, just 1 night. Complete checkout.
* Go back to the product page and observe that the booked date(which is unavailable) has the `partial_booked` class applied as well as the next day.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by madeincosmos** [comment] 2018-11-26 14:11
@woocommerce/extendables can we get someone input on this?

**Comment by dougaitken** [comment] 2018-11-29 13:43
Customer in 8433091-hc reached out about this as well. 
`https://www.samajubiluthyrning.se/shop/renault-master-l3h2/`

> if the car is booked - it only says partially booked, instead of booking is not possible.

They passed on this Issue link and confirmed their scenario matches this problem

**Comment by roykho** [comment] 2019-03-02 04:17
I can not replicate this. After checking out with 1 day booked. Coming back to the product, I see that same day is fully booked and the next day is still available to be booked. ![](https://cld.wthms.co/IbfS19+) Closing this issue for now. Please re-open if issue persists.

**Comment by jessepearson** [comment] 2019-03-05 14:49
@roykho Was that an Accommodation or Bookable product? When selecting one night by selecting a check in and then check out day, both days should show partially booked.

I believe the actual issue here is that if you select "today" as the check in, and then select a check out, "today" remains partially available even though it isn't available at all.

![](https://cld.wthms.co/5x4wxN+)
Image Link: https://cld.wthms.co/5x4wxN

**Comment by roykho** [comment] 2019-03-05 15:01
@jessepearson that was with Accommodations. Note that we no longer show partially booked days.

**Comment by jessepearson** [comment] 2019-03-05 15:25
@roykho I am using Bookings 1.13.2 and Accomm 1.1.5 and I got what you see above with an Accomm product. 

I am confused if partially booked days are now (or will be) removed from Accomm completely, as I would think this would break the functionality of being able to check in when someone is checking out, and vice versa.

**Comment by bor0** [comment] 2019-03-06 11:11
The reason you're seeing that is because it seems we missed releasing Accommodation Bookings: https://github.com/woocommerce/woocommerce-accommodation-bookings/blob/master/changelog.txt#L3-L4

cc @laurendavissmith

**Comment by jessepearson** [comment] 2019-03-06 12:44
After talking with Boro in Slack, I understand this better now, but the original issue still remains. 

If "today" only has check out available, it is able to be selected. 

![](https://cld.wthms.co/mgwfmg+)
Image Link: https://cld.wthms.co/mgwfmg

**Comment by laurendavissmith** [comment] 2019-03-06 19:23
@bor0 will you add this to your list to release

**Comment by bor0** [comment] 2019-03-07 13:14
With latest `develop` from Bookings I get some weird results:

1. If you save a product as "Accommodation product", on next page reload it goes back to "Bookable product"
2. I get this in the error log when I open the product on the frontend:
```
[Thu Mar 07 14:11:15.227923 2019] [php7:notice] [pid 3202] [client ::1:61160] PHP Fatal error:  Uncaught Error: Call to undefined method WC_Product_Accommodation_Booking::get_check_times() in /Users/bor0/dev/ext/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking-date-picker.php:32\nStack trace:\n#0 /usr/local/var/www/wordpress/wp-includes/class-wp-hook.php(286): WC_Accommodation_Booking_Date_Picker->add_accommodation_posted_data(Array, Object(WC_Product_Booking), 1)\n#1 /usr/local/var/www/wordpress/wp-includes/plugin.php(208): WP_Hook->apply_filters(Array, Array)\n#2 /Users/bor0/dev/ext/woocommerce-bookings/includes/booking-form/class-wc-booking-form.php(597): apply_filters('woocommerce_boo...', Array, Object(WC_Product_Booking), 1)\n#3 /Users/bor0/dev/ext/woocommerce-bookings/includes/booking-form/class-wc-booking-form.php(769): WC_Booking_Form->get_posted_data(Array)\n#4 /Users/bor0/dev/ext/woocommerce-bookings/includes/admin/class-wc-bookings-ajax.php(165): WC_Booking_Form->calculate_booking_cost(Array)\n#5 /usr/local/var/www/wordpress/wp-includes/class-wp-hook.php(286): WC_Bookings_ in /Users/bor0/dev/ext/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking-date-picker.php on line 32, referer: http://localhost:8080/wordpress/product/acc2/
```

I assume it has to do with the composer updates. It works fine with `master` WooCommerce Bookings.

@laurendavissmith I also think we should address this issue and @jessepearson's one before releasing this

**Comment by bor0** [comment] 2019-03-07 13:15
@jessepearson shouldn't check-in/check-out times be available for Booking? That's how I always understood Accommodation is supposed to work

**Comment by jessepearson** [comment] 2019-03-11 11:55
> shouldn't check-in/check-out times be available for booking? That's how I always understood Accommodation is supposed to work

@bor0 Yes, but in this instance, the day appears to be available for selection, but in reality it isn't because only check out is available and you're not able to select a check in date before it.

**Comment by madeincosmos** [comment] 2019-06-14 09:27
One more customer reporting this in 2108399-zen, reproduced with Bookings 1.14.4 & Accommodations

I'm testing a single hotel room with availability 1. Making a booking on 17th-20th June should make 17th unavailable for future booking:

![Screenshot](https://cld.wthms.co/sS52tM+)
Screenshot: https://cld.wthms.co/sS52tM

However, once I make that booking, 17th is still showing as available in the calendar:

![Screenshot](https://cld.wthms.co/UjYNCJ+)
Screenshot: https://cld.wthms.co/UjYNCJ

As a customer I'd find it super confusing. If a day is green in the calendar, I'd expect I can click on it and make a booking. Binary choice between available / not available may work fine for regular bookable products, but Accommodation needs 4 different states: available / not available / available for checkin / available for checkout. Reducing it to only two states is guaranteed to cause confusion.

@olaolusoga @kyleaparker @laurendavissmith can we revisit the UX for accommodations calendar? This seems to be quite a big pain point now.

**Comment by NickKellett** [comment] 2019-06-21 16:47
My client site sees this behaviour as well, using Woocommerce 3.6.4, Bookings 1.14.5, and Accommodations 1.1.8. They are also confused why a) a start date is available for booking that night is actually booked, and b) the triangle for check-in date disappeared. Unfortunately they are in the middle of camping season and so a lot of reservation calls are about this issue. I'd be happy to test a hotfix if one becomes available.

**Comment by reykjalin** [comment] 2019-06-21 17:49
2122409-zen seems to be seeing this same issue.

**Comment by alancolyer** [comment] 2019-06-24 08:38
same issue here, reported by a client. using bookable product product type now with an end time set instead of accommodation booking to get around the availability being incorrect.

**Comment by rwaynick** [comment] 2019-06-24 16:04
Also reported in 13611648-hc. User would prefer multiple states like @madeincosmos mentioned above.

**Comment by olaolusoga** [comment] 2019-06-24 20:58
>Accommodation needs 4 different states: available / not available / available for checkin / available for checkout.

@madeincosmos can you explain the value of having available for checkin / available for checkout states (which I'm assuming would be the partially booked triangles)?

From the screenshots, seems like the product should be making the first night unavailable/booked, and the last day open, instead of how it's currently operating. Once a person books, why would they need to see available for checkin/checkout on the product page calendar? and if a person who hasn't booked views the calendar, what's the value of showing them an available for checkin or checkout state? Isn't the objective for store owners to convert folks (get customers to book by showing available, and unavailable dates)?

**Comment by alancolyer** [comment] 2019-06-24 21:20
@olaolusoga hope you don't mind me answering - the first day of an existing booking needs to be available to select as the end date of a new booking, but it can't be a start date - this is why it differs. I'd agree that it needs a separate status to denote that so there is the option of theming it differently, although I think the end date should be open like you say as it doesn't make any difference to someone making a new booking.

I just wound up adding custom classes for the first day on my client's site. After some thought it seemed like the clearest way to communicate what dates are bookable was to have a partial status for the day just before a fully booked day.

Had to do a quick & dirty bit of js to make that happen but a built in solution would be much much better. If anyone wants a copy of the script drop me a line.

**Comment by olaolusoga** [comment] 2019-06-24 22:14
Thanks for sharing that @alancolyer , makes sense.

**Comment by madeincosmos** [comment] 2019-06-25 10:26
I agree with @alancolyer, I don't mind the last day of a previous booking to be showing as fully available, but first day of a booking showing as available is utterly confusing to customers.

**Comment by olaolusoga** [comment] 2019-06-28 14:56
Thanks for the context y'all.

We're going to reintroduce the partially booked indicator in Accommodation bookings to fix the issue y'all are raising. It will work exactly like it did previously. The start and end dates of a booking will be marked as partially booked.

**One small adjustment we'll be making:** rotating the end dates partially booked indicator 180°, so it marks the top left half of the square (the morning part) as booked—the start date indicator marks the bottom right (night time)

**Example**
<img width="300" alt="Screen Shot 2019-06-28 at 10 55 06 AM" src="https://user-images.githubusercontent.com/1382943/60351182-3b8f4c80-9993-11e9-9cc6-9fd1f6b05b0a.png">

**Comment by NickKellett** [comment] 2019-07-05 21:18
Will this be part of the next release, and is there some kind of ETC on that?

**Comment by MCKLtech** [comment] 2019-10-09 23:26
Any update on this? We're getting valid complaints from customers that it is confusing. They are booking an apartment, coming back to check the calendar, and they see the first and last days as 'available' 

I know it's somewhat user error but this is confusing and we should at least have the option to display the triangles again.

**Comment by alancolyer** [comment] 2019-10-10 07:36
+1 for an updste, been waiting for this

**Comment by laurendavissmith** [comment] 2019-10-10 20:00
Just moved this into our sprint board so we should have it done soon

**Comment by Zaffy-S** [comment] 2019-10-18 12:45
As someone who has made plenty accommodation sites and has worked in accommodation, I  think  the whole concept of showing "partially available days" is unnecessary because of the check in time rule.
When a room is available for a day, that means the room is available **after** the check in time. It doesn't matter if the room was booked the previous time or not. It doesn't matter if there were other guests there earlier that morning cause they will have to check out  before the next guest checks in.
What matters is if the room is available for the night. Rooms are booked per overnight not per day.
How many nights the client will stay in matters, not when he will leave the hotel (usually the next morning).
Our clients are confused about the partial availability, they don't really get the half triangles. 

In any case, the latest version of the plugin is wrong cause it doesn't show any kind of reservation for the first day of the booking period, which can lead to double bookings.

**Comment by superdav42** [comment] 2019-10-22 16:47
After looking at this issue it's just become more complex. Partial booking triangles are a poor customer experience especially when there can be more than one room booked as this would mark potentially all days an partially booked so it would be hard to see what is available for check-in and what isn't. 

The alternative to partially booked is changing the availability so the check-in day is unavailability for new bookings makes the first date picker work fine but would block picking the check-out day when an existing bookings has a check-in on the same day as the the desired checkout date. 

Really the best solution become what is most complicated which is to have separate calendars for checkout and checkin. Currently both calendars share the availability but ideally we would have different availability for checkin and checkout. I'll explore if this would even be feasible.

**Comment by jessepearson** [comment] 2019-10-22 22:19
@superdav42 If that path is going to be taken, I would think it would be more beneficial to put that logic in the main booking plugin. This would benefit those store admins that want to restrict start and end days to certain days of the week and such. I can see it working for vehicle rentals, room rentals, etc.

**Comment by Zaffy-S** [comment] 2019-10-28 21:19
Ok looking at this again can someone please tell me what does the Accommodation Bookings add to the Bookings Plugin functionality?
I deactivated it and the only thing missing seem to be the confusing limited availability triangles.
I can only think of accommodation that is bookable per hours and not per night?

**Comment by laurendavissmith** [comment] 2020-01-28 21:07
Removing @superdav42 for now, has a PR we just need to clean it up and ensure its ready for release

**Comment by roykho** [comment] 2020-02-03 21:50
Closed as this PR states this issue is not reproducible. https://github.com/woocommerce/woocommerce-bookings/pull/2753

**Comment by NickKellett** [comment] 2020-02-03 22:07
When I click the link to the PR i get a 404. It is highly confusing at this point what is going to be fixed or not fixed. We had a really complicated season last year due to the confusion of large numbers of clients seeing a calendar that seems to indicate a date is free when it isn't (leaving aside the whole triangles debate). if this issue is closed, can we at least request that https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/235 be fixed ASAP?

**Comment by roykho** [comment] 2020-02-03 23:21
@NickKellett - there is a potential fix for #235 in PR review. We'll see if that goes through.

**Comment by MCKLtech** [comment] 2020-09-03 15:03
Did 'the triangles' ever get put back in? We still have clients complaining about it.

For context, each calendar is unique to an apartment so the check in/checkout day with a triangle was really popular.

**Comment by alancolyer** [comment] 2020-09-03 17:45
> Did 'the triangles' ever get put back in? We still have clients complaining about it.
> 
> For context, each calendar is unique to an apartment so the check in/checkout day with a triangle was really popular.

Nope. I gave up hope myself. Having the option (atleast a classname we can style) in there would have prevented many issues reported by customers using the calendar and our unhappy clients. 

So far we have used wc bookings with 3 clients, and we have 3 clients constantly querying if the availability is correct due to confusing presentation issues like this one, and cryptic error messages like "there are a total of 0 spaces remaining on [date that is marked as available]" or "the minimum duration is 3" when you have 3 blocks selected (actually you need 4, as in 3 nights). A few touches on points like these would go a long way.

However I think we will be finding another solution that makes it clear to the user what is available and what is not while booking, its sadly just not worth the ensuing support time and confused customers.

**Comment by MCKLtech** [comment] 2020-09-03 17:50
Totally agree Alan.

Can anyone find the code/style that was removed? Was it part of WC Accomodation or WC Bookings?

**Comment by bor0** [comment] 2020-09-07 12:15
I am reopening this issue since there's a lot of movement going on. Removing the triangles was a design decision that we may need to re-think. There's a stale PR #230 attached to this issue.

**Comment by zdenys** [comment] 2021-01-29 11:13
Another case in 27355337-hc.

**Comment by enricocurro** [comment] 2021-04-06 17:11
CSS changes are not enough to customize the first day of each week, but... the fix is feasible in a very simple way:

+ 6 lines of code on frontend.js
+ 2 lines of code in class-wc-bookings-wc-ajax.php
+ 2 lines of code in class-wc-bookings-controller.php
(woocommerce-booking plugin files)

The whole DOES NOT touch all the other features of the plugins in the least, it only adds 2 arrays for the check-in and check-out dates which, if filled in, add a class on the calendar boxes:
<img width="354" alt="Schermata 2021-04-06 alle 18 54 05" src="https://user-images.githubusercontent.com/34400021/113750070-9e864980-970a-11eb-825b-1cba1cf3ded3.png"><img width="262" alt="Schermata 2021-04-06 alle 19 00 20" src="https://user-images.githubusercontent.com/34400021/113750085-a34afd80-970a-11eb-95ea-9d75fda939ee.png">

To do this I had to use https://unminify.com/ for the frontend.js file, because I proposed to Automattic to add the changes myself to a branch of the repo to let them test my work, but they replied that they will not share that file with me and that if I needed I could have the customization developed by paying one of their developers ... after a total wait of two months to get an answer on this.

Is it possible for a 250$/year plugin??

**Comment by MCKLtech** [comment] 2021-04-06 17:16
Looks good @enricocurro That's actually what it used look like before the changes.

As for the cost, Accommodations is free and is only an add on to the Booking Plugin (Which is paid). At this point though, it should be rolled into the main plugin and get proper support.

**Comment by enricocurro** [comment] 2021-04-06 17:22
Yes, exactly: Accommodations is useless without the paid plugin and the changes I have indicated must necessarily be made in the main plugin, not in the Accommodations extension.

The calendar, on the javascript side, is controlled entirely and exclusively by the script `./woocommerce-booking/dist/frontend.js` so the problem arises for the Accommodation part, but it originates from the code of the paid plugin.

**Comment by NickKellett** [comment] 2021-04-06 17:56
I've been reluctant to provide much criticism on this bug since it's open source and technically "free". But just to provide some feedback to Automattic in case it helps with your decision-making: this free add-on made it possible for me to provide a customized campground reservation system that utilized numerous other paid Woocommerce plugins (beyond just Bookings). It was a great solution while it worked, campground visitors loved it, and it led to a fairly substantial amount of revenue to yourselves for the wide variety of premium plugins we paid for each year. Sadly the confusion over what is and isn't bookable has made it impossible to continue using it. @MCKLtech suggestion to roll the functionality into the Bookings plugin, or making it a premium plugin itself, might help overcome the issues that are caused by it being downstream from the Bookings code. I hope that information helps.

**Comment by kg69design** [comment] 2021-05-08 19:14
Booking's start/end css-classes will be helpfull in this situations to make proper calendar-view.

**Comment by selectedselections** [comment] 2021-10-19 21:44
Reported in 4380508-zen

**Comment by pxwm** [comment] 2021-10-20 08:17
> CSS changes are not enough to customize the first day of each week, but... the fix is feasible in a very simple way:
> 
> * 6 lines of code on frontend.js
> * 2 lines of code in class-wc-bookings-wc-ajax.php
> * 2 lines of code in class-wc-bookings-controller.php
>   (woocommerce-booking plugin files)
> 
> The whole DOES NOT touch all the other features of the plugins in the least, it only adds 2 arrays for the check-in and check-out dates which, if filled in, add a class on the calendar boxes: <img alt="Schermata 2021-04-06 alle 18 54 05" width="354" src="https://user-images.githubusercontent.com/34400021/113750070-9e864980-970a-11eb-825b-1cba1cf3ded3.png"><img alt="Schermata 2021-04-06 alle 19 00 20" width="262" src="https://user-images.githubusercontent.com/34400021/113750085-a34afd80-970a-11eb-95ea-9d75fda939ee.png">
> 
> To do this I had to use https://unminify.com/ for the frontend.js file, because I proposed to Automattic to add the changes myself to a branch of the repo to let them test my work, but they replied that they will not share that file with me and that if I needed I could have the customization developed by paying one of their developers ... after a total wait of two months to get an answer on this.
> 
> Is it possible for a 250$/year plugin??

Hi enricocurro

We are experience the same issue and having contacted support we are no further forward with a solution.
I like the idea of your temporary fix and wanted to check if it would be possible if you could post your code so we can consider using. Our other option was to check the original code that I think was in v1.1.3 and see if we can write our own front end solution.

Regards
SteveB

**Comment by enricocurro** [comment] 2021-11-17 19:08
Here I am.. sorry man I was busy with a project

**./dist/frontend.js** 
(somewhere)


        ......this.customData.resources_assignment && (n.class = ["partial_booked"]); }

        // this part already exist, I cloned it for start and end dates below
        this.bookingsData.partially_booked_days &&
            this.bookingsData.partially_booked_days[l] &&
            ("automatic" === this.customData.resources_assignment || this.bookingsData.partially_booked_days[l][0] || this.bookingsData.partially_booked_days[l][o]) &&
            (n.class = ["partial_booked"]);
                        
        this.bookingsData.start_dates &&
            this.bookingsData.start_dates[l] &&
            ("automatic" === this.customData.resources_assignment || this.bookingsData.start_dates[l][0] || this.bookingsData.start_dates[l][o]) &&
            (n.class.push("start_dates"));
        
        this.bookingsData.end_dates &&
            this.bookingsData.end_dates[l] &&
            ("automatic" === this.customData.resources_assignment || this.bookingsData.end_dates[l][0] || this.bookingsData.end_dates[l][o]) &&
            (n.class.push("end_dates"));
        
        var f = i.get_number_of_days(this.customData.booking_duration, this.$form, ........



**./includes/class-wc-bookings-wc-ajax.php**
function _find_booked_day_blocks_
row 188~
        

          $args['partially_booked_days'] = $booked['partially_booked_days'];
          $args['fully_booked_days']     = $booked['fully_booked_days'];
          $args['unavailable_days']      = $booked['unavailable_days'];
          // start added
          $args['start_dates']           = $booked['start_date'];
          $args['end_dates']             = $booked['end_date'];
          // end added
          $args['restricted_days']       = $product->has_restricted_days() ? $product->get_restricted_days() : false;




**./includes/class-wc-bookings-controller.php**
function _find_booked_day_blocks_
row 323


          foreach ( $bookings as $booking ) {
              $check_date = $booking['start'];
              // start added
              $booked_day_blocks[ 'start_date' ][ date( $default_date_format, $booking['start'] ) ][ $booking['res'] ] = 1;
              $booked_day_blocks[ 'end_date' ][ date( $default_date_format, $booking['end'] ) ][ $booking['res'] ] = 1;
              // end added

              while ( $check_date <= $booking['end'] ) {
                  .....



Cheers 🍻

**Comment by enricocurro** [comment] 2021-11-17 19:27
Ah, obviously at that point the only css needed is this:


    // style for all partial booked days (start and end dates)
    .wc-bookings-date-picker .ui-datepicker td.partial_booked a.ui-state-default:after {
        content: "";
        position: absolute;
        bottom: 0;
        left: 0 !important;
        right: 0;
        top: 0 !important;
        z-index: -10;
        background-image: url(../images/triangle_cal.png);
        background-repeat: no-repeat;
        background-position: center center;
        background-size: 100% 100%;
        border: none !important;
        transform: rotate(0deg);
    }

    // overwrite style only for star dates
    .wc-bookings-date-picker .ui-datepicker td.partial_booked.start_dates a.ui-state-default:after {
        transform: rotate(180deg);
    }

**Comment by pxwm** [comment] 2021-11-23 15:43
Hi enricocurro

Many thanks - much appreciated

Regards
SteveB

**Comment by csmcneill** [comment] 2022-03-16 19:43
I encountered another incident of this issue in 4831440-zen:

- [Accommodation Booking](https://github.com/woocommerce/woocommerce-accommodation-bookings/files/8270070/woocommerce-accommodation-bookings.1.1.26.zip)
- [Global Rules](https://github.com/woocommerce/woocommerce-accommodation-bookings/files/8270083/bookings-global-rules-2022-03-16.zip)

When booking on 17 June, it only blocks off 18 June and indicates that 17 June is partially booked:

![Markup on 2022-03-16 at 14:38:49](https://user-images.githubusercontent.com/82999806/158676636-ba18cb8d-2306-44a1-bc18-57c3171b7d8f.png)

This is likely because the check-in time is at 16:00, which means that—technically—the rest of that day prior to 16:00 is "available." This allows customers to book that date ad infinitum.

However, if you book **16 June**, then 17 June suddenly becomes unavailable:

![Markup on 2022-03-16 at 14:41:41](https://user-images.githubusercontent.com/82999806/158676692-52345a56-d21e-4e8f-bbaf-d80fb6a56f4e.png)

![Markup on 2022-03-16 at 14:42:26](https://user-images.githubusercontent.com/82999806/158676716-d78bf323-5688-4b09-b95e-4e0a6483e448.png)

Edit:

Tested this further. If I book 14 June, that leaves 14 June and 15 June as partially booked:

![Markup on 2022-03-16 at 14:56:57](https://user-images.githubusercontent.com/82999806/158679700-26ca4b0f-f740-45a3-8bad-f7ff84214a48.png)

The only way I can get 14 June to be blocked off is if I have both 13 June and 14 June booked:

<img width="443" alt="Markup 2022-03-16 at 14 58 11" src="https://user-images.githubusercontent.com/82999806/158679791-a4f8e900-c0e5-4b34-83b4-5fb252bf2b54.png">

**Comment by pxwm** [comment] 2022-03-18 15:38
Hi csmcneill

I decided to disable the accommodation plugin and revert to using the Woocommerce Booking plugin on its own.
The main reason is that it then blocks out the whole day, so for your example it would block the 16th.

I based this process on that it appears the majority of hotels/accommodation tend to just use the full day as the booking and just add a note to indicate the check-in and check-out time.

I've found this less confusion to visitors to the site and it removes the issue with partially booked days.
Therefore the check-in/start date will show as fully booked and for your example of the 16th - it would show this as fully booked and the 15th and 17th would be free 

Hope that helps.

Regards
SteveB

**Comment by xMarcoX** [comment] 2022-05-25 09:54
Same issue here, we have 12h block to simulate half days and when you book 2 blocks (a full day) it will show as follows.
*buffer time is set to 0

![screen](https://user-images.githubusercontent.com/17478574/170235279-05073bf0-7920-4b1f-bc23-6c5219e39204.jpg)

**Comment by pehaa** [comment] 2022-05-30 07:09
One more report here 5254603-zd-woothemes
I tested on conflict-free site with Storefront, WooCommerce Bookings and WooCommerce Accommodation Bookings and could replicate the issue.

The product is a virtual accommodation product without resources.

One night booking is not correctly marked in the calendar on the product page.
For longer bookings first day is not correctly marked in the calendar.

**Comment by sukafia** [comment] 2022-06-17 09:46
@jeffpaul we're getting some heat on this issue. Would you be able to give us an ETA on this?

**Comment by jeffpaul** [comment] 2022-06-17 20:06
@sukafia this one has not been picked up by anyone on the team, but I'll bring it up in our team meeting next week and look to get this scheduled.

**Comment by jeffpaul** [comment] 2022-07-06 16:41
@sukafia note that we had a design/approach discussion on this today and believe to have an approach that should cover all cases, a PR will get up and then go through the review/testing cycles at which point I'll have a better sense of timing for this getting into a potential release.

**Comment by thelogicwizards** [comment] 2022-07-11 15:46
> @sukafia note that we had a design/approach discussion on this today and believe to have an approach that should cover all cases, a PR will get up and then go through the review/testing cycles at which point I'll have a better sense of timing for this getting into a potential release.

Thanks for the update, @jeffpaul - we look forward to any future updates you can share on our ETA!

**Comment by thelogicwizards** [comment] 2022-09-22 14:27
Hey, @dkotter - just checking in to ask about any updates on an ETA for our PR to be merged on this. Any insights are appreciated!

**Comment by jeffpaul** [comment] 2022-09-22 15:08
@thelogicwizards the related PRs are in QA, amongst many other fixes for Accommodation Bookings and ~2 dozen other extensions under our teams support.  Feel free to subscribe to updates on those PRs as the best way to see them progress across the several review/testing cycles before getting into a release.  If there's an urgent or important need to bump the priority here, then please share those details so we can adjust accordingly... thanks!

**Comment by lynnjat7** [comment] 2022-12-12 15:52
This is the PR for the fix for this issue, if anyone is looking:
https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/303

This PR depends on a fix made to the Bookings core plugin, that PR is currently blocked, here:
https://github.com/woocommerce/woocommerce-bookings/pull/3378

**Closed** 2023-05-12 12:28 UTC
Labels: priority: high, type: bug

**Comment by ibrahim-kardi** [comment] 2025-09-30 01:57
I have configured : https://www.youtube.com/watch?v=Wbj79yqF6D8
