### ISSUE TITLE
Accommodations compatibility with Bookings 1.10

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-accommodation-bookings#90] opened 2017-02-27 21:37 UTC
```
PHP Fatal error:  Class 'WC_Product_Booking' not found in .../woocommerce-accommodation-bookings/includes/class-wc-product-accommodation-booking.php on line 10
```

#### Affected ticket(s)

557875-zd-woothemes
559615-zd-woothemes
558257-zd-woothemes
558301-zd-woothemes
552989-zd-woothemes

#### What I expected

To activate Accommodations and it would activate.

#### What happened instead

It threw a fatal and died.

#### Steps to reproduce the issue

1. Load Bookings 1.10.0 Beta 1
1. Activate Accommodations
1. 💥 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by Elan42** [comment] 2017-04-05 23:25
This is still happening !

**Comment by bor0** [comment] 2017-04-06 08:10
This seems to be working fine as far as I tested. Can you retest using 1.10.0 Bookings and latest Accommodation Bookings?

**Comment by Elan42** [comment] 2017-04-06 08:43
I have WooCommerce Accommodation Bookings: Version 1.0.7
And WooCommerce Bookings: 1.9.12
I see only update notification for "WooCommerce Bookings" 1.9.12 -> 1.10.0

When I update, I have a fatal error and WP goes boom.

**Comment by stuartduff** [comment] 2017-04-07 17:00
@roykho Could we have this deployed as v1.0.8 asap please as v1.0.7 is creating a fatal error that's taking site offline. 

Cheers

**Comment by mgibbs189** [comment] 2017-04-07 20:30
```
Fatal error: Class 'WC_Product_Booking' not found in [...]/plugins/woocommerce-accommodation-bookings/includes/class-wc-product-accommodation-booking.php on line 10
```

**Comment by mgibbs189** [comment] 2017-04-07 20:45
@bor0 @stuartduff 

[A] woocommerce-bookings/woocommerce-bookings.php:52

```php
add_action( 'plugins_loaded', array( $this, 'includes' ) );
```

[B] woocommerce-accommodation-bookings/includes/class-wc-accommodation-bookings-plugin.php:78

```php
add_action( 'woocommerce_loaded', array( $this, 'includes' ), 20 );
```

[Solution] woocommerce_loaded is running BEFORE plugins_loaded, hence the fatal error. You might want to consider changing the hook from `woocommerce_loaded` to `plugins_loaded` (keeping priority=20) as well.

This resolved the issue for me. I'm still seeing an (unrelated) PHP notice afterwards:

```
Warning: Declaration of WC_Product_Accommodation_Booking::get_duration_type() should be compatible with WC_Product_Booking::get_duration_type($context = 'view') in .../plugins/woocommerce-accommodation-bookings/includes/class-wc-product-accommodation-booking.php on line 116
```

**Comment by Elan42** [comment] 2017-04-09 18:13
I've also got this after a while:
Fatal error: Call to a member function get_title() on boolean in [...]/wp-content/plugins/woocommerce-bookings/includes/emails/class-wc-email-booking-confirmed.php on line 85

Had to comment that line and enter admin to resolve (and remove comment).

**Comment by bor0** [comment] 2017-04-10 06:03
The errors you are describing should be already fixed by https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/94 in the next release. We're planning to release sometime this week, as soon as we close all issues in 1.0.8.

**Comment by madeincosmos** [comment] 2017-04-10 08:55
One more user reporting the same problem in 557875-zd-woothemes.

**Comment by kristinaplauche** [comment] 2017-04-10 16:16
Another ticket 552989-zd-woothemes.

@bor0 @roykho I appreciate wanting to close the open issues, but these customers are getting fatal errors and their entire site cannot do business.  The only way to fix it is uploading the pre-release version via ftp. 

Can we please see about getting this fix deployed asap?  Some issues are better than a fatal error that effectively puts them out of business.

**Comment by bor0** [comment] 2017-04-10 16:52
Per agreement with @roykho and @gedex we've decided 1.0.8 to be 3.0 compat fixes and will work on 1.0.9 to clean the other issues. Release follows.

**Closed** 2017-04-10 16:56 UTC
Labels: [Pri] CRITICAL, [Type] Bug

**Comment by giuliaPregusta** [comment] 2017-05-08 21:27
Hi! I have:
WooCommerce 3.0.5
WooCommerce Bookings 1.10.0
WooCommerce Accommodation Bookings 1.9.15

when I try to publish an accomodation product, it appears me the FATAL ERROR:
Fatal error: Uncaught exception 'Exception' with message 'Invalid data store.' in /home/pregusta/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php:90 Stack trace: #0 /home/pregusta/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(123): WC_Data_Store->__construct('product-accommo...') #1 /home/pregusta/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php(124): WC_Data_Store::load('product-accommo...') #2 /home/pregusta/public_html/wp-content/plugins/woocommerce-bookings/includes/class-wc-product-booking.php(20): WC_Product->__construct(12361) #3 /home/pregusta/public_html/wp-content/plugins/woocommerce-bookings/includes/class-wc-product-class-loader.php(33): WC_Product_Booking->__construct(12361) #4 /home/pregusta/public_html/wp-content/plugins/woocommerce-bookings/includes/addons/accommodation-booking.php(13): WC_Product_Skeleton_Booking->__construct(12361) #5 /home/pregusta/public_html/wp-content/plugins/woocommerce/includes/admin/meta- in /home/pregusta/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php on line 90

What can I do to solve it?!
thanks a lot for help!!

**Comment by bor0** [comment] 2017-05-09 09:00
Hi @giuliaPregusta, latest Bookings is 1.10.1 and Accommodation Bookings is 1.0.9. It's unclear to me the Accommodation Bookings version that you're using, can you please confirm them?
