### ISSUE TITLE
Persons types not duplicated

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce-accommodation-bookings#226] opened 2019-08-20 19:35 UTC
#### Affected ticket(s)

2243736-zen

#### What I expected

I expected that duplicating an Accommodation product would duplicate the product exactly. 

#### What happened instead

Person types are not duplicated to the new product.

#### Steps to reproduce the issue

1.  Create an Accommodation product
2. Enable Person Types
3. Add a Person Type
4. Publish the product
5. Duplicate the product using the core duplicate link on the products page
6. Check the new product for person types

Person types remain enabled, but are missing.

-------------------

- [ ] Issue assigned to next milestone.
- [x] Issue assigned a priority (will be assessed by maintainers).

**Comment by bor0** [comment] 2020-09-22 11:22
Duplicate of #212 which is already fixed.

**Closed by bor0** 2020-09-22 11:22 UTC
Labels: [Pri] Low, [Type] Bug
