### ISSUE TITLE
Resource availability calculated incorrectly 

### ISSUE THREAD

**Issue by bulgaru** [woocommerce/woocommerce-accommodation-bookings#127] opened 2017-06-15 13:23 UTC
#### What I expected

I have 15 rooms. I book 5 for days 1 to 5. All 5 days are shown as partially booked in the calendar. I can still book another 10 rooms for each of the days 1 to 5.

#### What happened instead

I have 15 rooms. I book 5 for days 1 to 5. All 5 days are shown as fully booked in the calendar. I cannot book another room for each of the days 1 to 5.

#### Steps to reproduce the issue

1. Create a resource Rooms and set it to 15.
2. Create accommodation product and assign the resource to the product.
3. Add persons to the product and set each person to be as one booking (person per resource).
4. Booking 1: book rooms for 5 persons for days 1-5.
5. Booking 2: notice the calendar does not allow you to set date for days 1-5.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by jessepearson** [comment] 2017-06-15 16:44
Confirmed this as a bug, @mattyza not sure who you wanted assigned to this.

Both results are incorrect. Below are my settings:

General and persons:
![](http://cld.wthms.co/c1rNR+)
Image Link: http://cld.wthms.co/c1rNR

Resource settings:
![](http://cld.wthms.co/IJMjyw+)
Image Link: http://cld.wthms.co/IJMjyw

Result when resource is automatically assigned: ❌ 
![](http://cld.wthms.co/zK5t5+)
Image Link: http://cld.wthms.co/zK5t5

Result when resource is customer selected: ❌ 
![](http://cld.wthms.co/L6pjTl+)
Image Link: http://cld.wthms.co/L6pjTl

**Comment by bor0** [comment] 2017-06-16 11:29
Before working on this I believe we first want to have https://github.com/woocommerce/woocommerce-bookings/pull/1213 resolved first.

**Comment by jessepearson** [comment] 2017-06-16 11:50
Agreed.

**Comment by silicondales** [comment] 2017-06-26 11:34
Hi all,

Posting a "me too" for now, with a little more detail. This happens my side even without resources or persons in use, but multi-day bookings mark date as full on either first or second booking, even if there should be 20x (or 999x) rooms available.

This also means dates are marked as full when a pending booking is sitting across the dates, which is far from ideal.

Reported by customer but confirmed in a clean install.

**Comment by silicondales** [comment] 2017-06-26 11:39
![image](https://user-images.githubusercontent.com/17259256/27537502-13000d12-5a6c-11e7-91a4-4907518c9d2f.png)

above calendar relates to

![image](https://user-images.githubusercontent.com/17259256/27537558-516a3eba-5a6c-11e7-885a-b676c70d6907.png)

Product should allow up to 20x bookings, based on:

![image](https://user-images.githubusercontent.com/17259256/27537586-6a80fa9c-5a6c-11e7-8301-90dc0f6afe2c.png)

But 6 July is marked "fully booked".

**Comment by silicondales** [comment] 2017-06-26 11:40
So the "middle" date of the 5-7th booking is marked full, immediately.

**Comment by silicondales** [comment] 2017-06-28 13:34
Just about to do some testing with the fixes on master, and see if I can get this working as client is somewhat motivated to have this resolved :) if I can make any headway I may come back in with a PR. Note, I think I'm on the same issue (albeit presenting slightly differently) Or should I post a new one relating to the exact circumstances (which is something like "accommodation bookings incorrectly marking as fully booked")? @bor0 @jessepearson - mainly asking as there's a couple of underlying bookings fixes I think this is running into?

**Comment by jessepearson** [comment] 2017-06-29 18:41
@silicondales I believe the issue you are referring to is the same. We just released Bookings 1.10.4 and we were hoping it was going to help relieve this issue, but it appears it did not, I still have incorrect results :(

**Comment by budzanowski** [comment] 2017-07-05 08:06
@mattyza  @jessepearson  I have analysed the Critical bug and it looks like: `bookings` does everything correctly and in a clean fashion thanks to the @bor0  refactor. The problem starts when at the end of `WC_Bookings_Controller::find_booked_day_blocks`  the hook `woocommerce_bookings_booked_day_blocks` is called. `accommodation-bookings` are hooked to that with function `WC_Accommodation_Booking_Date_Picker::add_partially_booked_dates` which from what I understand is responsible to changing fully booked days at check in/out date to partially booked dates to indicate for example that other bookings may start/end on that dates. I am right now thinking what needs to change in `add_partially_booked_dates` to fix the issue but it looks like a lot but I yet need to think about good strategy how to handle this.

**Comment by silicondales** [comment] 2017-07-05 08:55
Yeah I didn't get even a good workaround when I was looking at this last week, and did not get a working result. Unfortunately, in our case, the client essentially wants to go to sleep until this is fixed, and we don't have any maintenance contract which inspires any activity here... therefore, we have a (paid up) backlog to concentrate upon. It looked to me like a similar rabbit hole @budzanowski fwiw!

**Comment by melindahelt** [comment] 2017-07-12 17:36
Also seeing this ins 601294-zd-woothemes

**Comment by bor0** [comment] 2017-07-14 10:26
This should be fixed by #134. Will sync with @budzanowski next week.

**Comment by silicondales** [comment] 2017-07-14 10:51
Will give this a blast in a test later today with the bookings / accommodation PRs and confirm working for my case...

**Comment by silicondales** [comment] 2017-07-20 11:43
Hey guys - just to confirm, the master bookings and accommodation bookings *fixes* the issue I experienced absolutely in all tests I have tried.

**Comment by bor0** [comment] 2017-07-20 11:44
@silicondales that's great to hear. Can you be more specific about which branch of accommodation bookings you tested? Was it master, or some other?

**Comment by silicondales** [comment] 2017-07-20 12:04
yeah I tested the most recent master on both bookings and accommodation, as of 15 mins ago. The issue was [the above](https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/127#issuecomment-311035317), and this is resolved using those.

**Comment by silicondales** [comment] 2017-07-20 12:05
(i.e. its not exactly the posted issue, but I believe it stems from similar root cause).

**Comment by silicondales** [comment] 2017-07-20 12:11
This includes the commit you just added, and that's been the charm for my issue. I will test some of the other scenarios which were failing too and comment back only if there's anything obviously going wrong. Nice work @bor0... praise will rarely surface on this stuff, but definitely a crisp internet high five from me :)

**Comment by bor0** [comment] 2017-07-20 14:05
@silicondales thank you for the kind words! It will be very bad from my side if I were to take all the credit for myself.

There's a whole team behind this, and I'm very happy that we reached a point where Bookings is faster and more stable in terms of bugs, which will allow us to focus on new features/enhancements in the future versions :)

**Comment by silicondales** [comment] 2017-07-20 14:07
Yeah I know - props to everyone. But I try to give credit when its due, because lord knows when things are going wrong there's plenty of criticism dished out :)

**Closed** 2017-07-24 10:04 UTC
Labels: [Pri] CRITICAL, [Type] Bug
