### ISSUE TITLE
When booking a year out, first day is fully booked when should be partially booked

### ISSUE THREAD

**Issue by geeklore** [woocommerce/woocommerce-accommodation-bookings#119] opened 2017-05-15 20:35 UTC
#### Affected ticket(s)
574150-zd-woothemes

#### What I expected
When booking a few nights a year out, I would expect the first day to be partially booked, allowing the day to still be used as a checkout day. This works for any booking short of 1 year.

#### What happened instead
When I book a year out, the first day is fully booked.

![see screen shot](http://cld.wthms.co/DG1Eh+)
Link: http://cld.wthms.co/DG1Eh

#### Steps to reproduce the issue
Create a simple Accommodations product, the only change is that you will need to allow bookings to be made over a year out.

![see screen shot](http://cld.wthms.co/x2zTk+)
Link: http://cld.wthms.co/x2zTk

Then book a few days, but make it over a year out.

The first day will be blocked out completely. 

WooCommerce `3.0.6`
WooCommerce Bookings `1.10.2`
WooCommerce Bookings Accommodations `1.0.9`

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by jessepearson** [comment] 2017-05-16 11:32
Confirmed, same results. Pretty funny how that happens.

**Comment by WPprodigy** [comment] 2017-09-11 15:49
Another report: https://woothemes.zendesk.com/agent/tickets/674246

**Comment by lindamork** [comment] 2018-10-10 16:36
Hoping for an update on when this piece of the 1.2 milestone might be tackled?

**Comment by mikkamp** [comment] 2020-05-07 16:22
As of the latest versions of Bookings and Accommodation Bookings it's not possible to select any day that is also a "checkin" day. So unable to reproduce the specific issue where it displays different for just a year out.

There are already two other high priority bugs which are tracking this problem, see:
https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/250
https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/243

No longer having the start day show up as "partially available" is caused by the following commit: https://github.com/woocommerce/woocommerce-accommodation-bookings/commit/0d42f97a9a474ad9865132bb10245576cef17d92
However even after reverting that the day shows as partially available but the availability count remains 0 so we are unable to retrieve a booking cost. This is because of restructuring withing Bookings itself.

So closing this issue in favour of one of the high priority issues.

**Closed by mikkamp** 2020-05-07 16:22 UTC
Labels: [Pri] Low, [Type] Bug
