### ISSUE TITLE
Accommodation product + auto-assigned resources = incorrect availability on booking dates

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-accommodation-bookings#87] opened 2017-01-16 10:01 UTC
#### Affected ticket(s)

508723-zd-woothemes

#### What I expected

Add a base cost to accommodation products with the use of resources. To do this, I've added one resource on a product with a base cost and quantity = 1:

![Screenshot](http://cld.wthms.co/3ZRu+) 
Screenshot: http://cld.wthms.co/3ZRu

#### What happened instead

When someone makes a booking on certain dates, and:

- The resource is **customer-selected**, these days show in calendar as not available:

![Screenshot](http://cld.wthms.co/TJXl+) 
Screenshot: http://cld.wthms.co/TJXl

- Same setup, resource is **automatically assigned**, all days are available even though I've made a booking:

![Screenshot](http://cld.wthms.co/OX2v+) 
Screenshot: http://cld.wthms.co/OX2v

This problem doesn't occur for simple bookable products, resource availability shows correctly in both cases.

#### Steps to reproduce the issue

1. Add two accommodation products with one resource each (quantity = 1).
2. Make the resources on one of these products auto-assigned, on the other one customer-selected.
3. Add two bookings - one for each product - on the same dates.
4. Observe that the first calendar is 100% available, while the other one correctly shows the day that should not be available.

Reproduced both with Bookings 1.9.15 and latest master.

-------------------

- [x] Issue assigned to next milestone.
- [x] Issue assigned a priority (will be assessed by maintainers).

**Comment by madeincosmos** [comment] 2017-01-31 09:57
@jessepearson any ideas what could be going on here?

**Comment by jessepearson** [comment] 2017-01-31 13:02
@madeincosmos Not sure off the top of my head. 

I confirmed the issue. When the resource is *Customer selected* vs *Automatically assigned*, the days booked do not show partially assigned. I also found that either way, they do not show fully booked properly, either.

Not able to create example products here due to Bookings Helper doesn't play nice with Accomm products.

**Comment by madeincosmos** [comment] 2017-02-02 13:33
Thanks! If there's anything else I can do here to speed this up, please let me know 😄

**Comment by jessepearson** [comment] 2017-02-09 14:25
I believe this is related to [Bookings 952](https://github.com/woocommerce/woocommerce-bookings/issues/952). I just tested against the latest master and it's worse now, as I am able to book the same days over and over again, even though the resource has an availability of 1. 

There most be code in Accomm that overrides what Bookings does and it's now broken due to the fix in Bookings.

**Comment by bor0** [comment] 2017-04-20 18:07
Not able to reproduce this anymore. Possibly fixed by #108. @jessepearson can you confirm? Thanks!

**Comment by jessepearson** [comment] 2017-04-20 18:33
I believe this is *almost* fixed, just wanted to note our discussion [over here](https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/109#issuecomment-295846529)

**Closed** 2017-04-25 05:59 UTC
Labels: [Pri] High, [Type] Bug
