### ISSUE TITLE
When booking a year from current month, costs not applied

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/woocommerce-accommodation-bookings#166] opened 2017-12-27 16:30 UTC
#### Affected ticket(s)

868591-zen

#### What I expected

When setting up an "Accommodation product" with rates based off of "Range of months", costs should always be applied to those months, whether they are in the current year, or a year in the future.

#### What happened instead

When setting up an "Accommodation product" with rates based off of "Range of months", costs are not applied to a year from whatever the current month is (ex: it is December 2017 now, so costs in December 2018 aren't working, just showing as $0.00). Only that month is affected.

#### Steps to reproduce the issue

1. Setup an "Accommodation product" with these settings for the "General" tab:

![http://cld.wthms.co/hPkAux](http://cld.wthms.co/hPkAux+)

2. Use these settings for the "Availability" tab:

![http://cld.wthms.co/YCNl7v](http://cld.wthms.co/YCNl7v+)

3. Use these settings for the "Rates" tab:

![http://cld.wthms.co/3wadxb](http://cld.wthms.co/3wadxb+)

Rates for December 2018 do not get applied, although you can see November and January rates apply correctly (as do all other rates for other months):

![http://cld.wthms.co/ciexko](http://cld.wthms.co/ciexko+)

Currently, the workaround is to add this:

![http://cld.wthms.co/vpFVQq](http://cld.wthms.co/vpFVQq+)

... but that's not ideal and would have to be changed each month.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by melindahelt** [comment] 2018-10-22 20:30
User came back again, same site, but slightly different issue.

Today (October 22nd) all bookings from Dec 1 to Dec 31 2019 (so over a year from now) were showing up at $0. November 2019 and January 2020 were priced as expected.

Used the above date range to override this, but customer was hoping it would be fixed by now.

**ALSO -- NOTE -- customer logs in as different clients for chat (customers own the license) but would like to be notified at shirley@5btech.net when this issue is fixed so they can be aware without the message being lost with their clients.** (I did not leave an open ticket, as the last one was closed due to low priority)

Images from today's troubleshooting as record:

Product was https://www.galenalodge.com/product/miners-yurt/

![](https://cld.wthms.co/yolRzW+)Image Link: https://cld.wthms.co/yolRzW

![](https://cld.wthms.co/4rB523+)Image Link: https://cld.wthms.co/4rB523

![](https://cld.wthms.co/0kGxm7+)Image Link: https://cld.wthms.co/0kGxm7

Additional steps taken today:

1. Used booking helper to export product/import into my test site. (removed the range of certain nights that we added above) and tested
2. Still showing up as $0 for December 2019 products (latest version of all plugins)

3. If you add a "standard room rate" that will display for December (rather than 0) but that is still the wrong price.

![](http://cld.wthms.co/zKMYAd+)Image Link: http://cld.wthms.co/zKMYAd

4. Created a new product from scratch, and confirmed above behavior.


copy of product from customer site -- remove the rate line for 12-01-2019 to 12-31-2019 before testing after importing product
[booking-product-23077-2018-10-22.zip](https://github.com/woocommerce/woocommerce-accommodation-bookings/files/2503279/booking-product-23077-2018-10-22.zip)

Changing priority on this, since it's still happening and customer was hoping for an update after almost a year.

**Comment by jessepearson** [comment] 2018-10-23 11:04
User came back again, same site, but slightly different issue.

Today (October 22nd) all bookings from Dec 1 to Dec 31 2019 (so over a year from now) were showing up at $0. November 2019 and January 2020 were priced as expected.

Used the above date range to override this, but customer was hoping it would be fixed by now.

**ALSO -- NOTE -- customer logs in as different clients for chat (customers own the license) but would like to be notified at `redacted` when this issue is fixed so they can be aware without the message being lost with their clients.** (I did not leave an open ticket, as the last one was closed due to low priority)

Images from today's troubleshooting as record:

Product was https://www.galenalodge.com/product/miners-yurt/

![](https://cld.wthms.co/yolRzW+)Image Link: https://cld.wthms.co/yolRzW

![](https://cld.wthms.co/4rB523+)Image Link: https://cld.wthms.co/4rB523

![](https://cld.wthms.co/0kGxm7+)Image Link: https://cld.wthms.co/0kGxm7

Additional steps taken today:

1. Used booking helper to export product/import into my test site. (removed the range of certain nights that we added above) and tested
2. Still showing up as $0 for December 2019 products (latest version of all plugins)

3. If you add a "standard room rate" that will display for December (rather than 0) but that is still the wrong price.

![](http://cld.wthms.co/zKMYAd+)Image Link: http://cld.wthms.co/zKMYAd

4. Created a new product from scratch, and confirmed above behavior.


copy of product from customer site -- remove the rate line for 12-01-2019 to 12-31-2019 before testing after importing product
[booking-product-23077-2018-10-22.zip](https://github.com/woocommerce/woocommerce-accommodation-bookings/files/2503279/booking-product-23077-2018-10-22.zip)

Changing priority on this, since it's still happening and customer was hoping for an update after almost a year.

**Comment by c-shultz** [comment] 2019-01-18 23:09
The root cause of this is actually in the main Bookings extension, so I'm closing this in favor of https://github.com/woocommerce/woocommerce-bookings/issues/2063

PR incoming. I expect this will be fixed by the 1.13.0 release of Bookings.

**Closed by c-shultz** 2019-01-18 23:09 UTC
Labels: [Pri] High, [Type] Bug
