### ISSUE TITLE
Error in Updating Accommodation Product Data via REST API: Unrecognized Product Type Response

### ISSUE THREAD

**Issue by ankitguptaindia** [woocommerce/woocommerce-accommodation-bookings#435] opened 2024-05-23 15:23 UTC
**Description:**  When attempting to update Accommodation Product Data using the REST API, the update fails. After sending the POST request, the response returns an error: **"type": "type is not one of simple, grouped, external, variable, and booking."** indicating that the provided product type is not recognized by the system.

![Screenshot 2024-05-23 at 8 47 15 PM](https://github.com/woocommerce/woocommerce-accommodation-bookings/assets/6384299/543d4993-4cb5-4356-b2d4-a093c280987c)

Reference taken for updating the product- https://woocommerce.github.io/woocommerce-bookings-api-docs/#update-a-bookable-product 

#### What I expected

Accommodation Products should also be updated via REST API. 

#### What happened instead

Doesn't update. 

#### Steps to reproduce the issue

https://github.com/woocommerce/woocommerce-accommodation-bookings/assets/6384299/61b28cab-5757-4e4a-be71-0745d386a80d

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by faisal-alvi** [comment] 2024-05-29 11:00
Closing as duplicate of #401

**Closed as completed by faisal-alvi** 2024-05-29 11:00 UTC
Labels: priority: low, type: bug
