### ISSUE TITLE
Overlapping Rates Calculation is Incorrect

### ISSUE THREAD

**Issue by DustinHartzler** [woocommerce/woocommerce-accommodation-bookings#209] opened 2019-02-01 20:51 UTC
#### Affected ticket(s)
1761730-zen
15856100-hc
8626144-hc 

#### What I expected
When multiple rates are specified, I expect the first line item in the list to be used and no others.

Here is my example accommodations product:
<img width="961" alt="screen shot 2019-02-01 at 15 44 35" src="https://user-images.githubusercontent.com/2293077/52148652-5fdf3b00-2638-11e9-97ad-f83ee59b1225.png">

If a date is selected for 2019-02-09 (Friday), I expect the rate to be $160.

#### What happened instead

But the rate is coming out as $295:
<img width="457" alt="screen shot 2019-02-01 at 15 46 33" src="https://user-images.githubusercontent.com/2293077/52148737-9d43c880-2638-11e9-9c23-554d7bfab15c.png">

This is $160 (top line item, specified for the week) + $200 (last line item, Friday / Saturday cost) - $65 (standard room rate).

This is incorrect.

#### Steps to reproduce the issue

- Create a new Accommodations product
- Create two different rates that cover the same date (like Range of Certain Nights and Range of Nights During)
- Try choosing the date to book and see the incorrect rate.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by htdat** [comment] 2019-02-28 07:03
This issue has been here for 26 days. Hope that we have an update for the user soon.

**Comment by DustinHartzler** [comment] 2019-04-04 18:36
Issue came up with [8626144-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=8626144) as well.

**Comment by ryanr14** [comment] 2019-06-10 22:52
I believe I've got another customer with this overlapping rules miscalculations in 2099967-zen.

They have the following Cost rules setup.

![https://cld.wthms.co/GDxtfo](https://cld.wthms.co/GDxtfo+)
Image link: https://cld.wthms.co/GDxtfo

According to this if you booked from Wednesday July 3rd to checking out Saturday July 6th. That price should TOTAL = $951. The problem is that it actually shows up as $1101, and I can't figure out what different pricing rules it is using to get that total. As soon as I remove the "Range of nights rule" it calculates correctly for that week of the 4th of July. But that breaks all other weeks that this rule should work just fine.

![https://cld.wthms.co/MN0kGg](https://cld.wthms.co/MN0kGg+)
Image link: https://cld.wthms.co/MN0kGg

**Comment by thekendog** [comment] 2019-06-11 13:30
Is this something that will be fixed soon?  Seems like a pretty big bug to leave sitting for over 4 months now.

**Comment by thekendog** [comment] 2019-07-22 15:50
Bump.  Still nothing?

**Comment by treibalen** [comment] 2019-10-10 11:11
Also reported in 15856100-hc

**Comment by c-shultz** [comment] 2019-12-13 20:22
The only solution I found was to add a new filter in Bookings (https://github.com/woocommerce/woocommerce-bookings/pull/2767) and add a hook for the filter in Accommodation Bookings: https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/234

If this is all merged in, it will require an update of both extensions to the latest version.

**Closed** 2019-12-16 20:05 UTC
Labels: [Pri] High, [Status] Has PR, [Type] Bug
